packages:
  - editors/*
  - examples/*

catalog:
  '@types/node': ^24.7.2
  rolldown: 1.0.0-beta.42
  rolldown-plugin-dts: ^0.16.11
  tsconfig-aliases: ^1.0.1
  typescript: ^5.9.3
  vitest: ^3.2.4

onlyBuiltDependencies:
  - esbuild
